version: '3'
services:
  foo:
    image: spring-boot-app:latest
    ports:
    - "8080:8080"

  bar:
    image: spring-boot-app:latest
    ports:
    - "8081:8080"

  baz:
    image: spring-boot-app:latest
    ports:
    - "8082:8080"
