version: '2.1'
services:
  foo:
     extends:
       file: app-compose.yml
       service: app
     ports:
     - "8080:8080"

  bar:
    extends:
      file: app-compose.yml
      service: app
    ports:
    - "8081:8080"

  baz:
    extends:
      file: app-compose.yml
      service: app
    ports:
    - "8082:8080"
